version: "3.7"

services:
  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Pass2021!
      POSTGRES_USER: fitofit
      POSTGRES_DB: fitofit
    ports:
      - 5432:5432

volumes:
  postgres-data:
