version: "3.7"

services:
  app:
    image: node
    command: sh -c "npm install && npm run dev"
    ports:
      - 3001:3001
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PGUSER: fitofit
      PGPASSWORD: Pass2021!
      PGDATABASE: fitofit
      PGHOST: postgres

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Pass2021!
      POSTGRES_USER: fitofit
      POSTGRES_DB: fitofit
    ports:
      - 5432:5432

  postgres-test:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Pass2021!
      POSTGRES_USER: fitofit
      POSTGRES_DB: fitofit
    ports:
      - 5433:5432

volumes:
  postgres-data:
